config/routes.rb
Rails.application.routes.draw do
  resources :members
  resources :posts
  resources :clean_blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "clean_blogs#index"
get '/' => "clean_blogs#index"
get  'about' 	=> 'clean_blogs#about'
get  'contact' 	=> 'clean_blogs#contact'
get 'result' => 'clean_blogs#result'
get 'podex' => 'posts#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :img, ImgUploader
  def self.search(search) #self.でクラスメソッドとしている
   if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      Post.where(['name LIKE ?', "%#{search}%"])
   else

   end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clean_blogs_controller.rb
class CleanBlogsController < ApplicationController
	layout "clean_blog"

	def index
		@posts = Post.all
	end

	def about
	end

	def post
	end

	def contact
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        SampleMailer.send_when_create(@member).deliver_now
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:name, :mailadd, :phonenum, :apply)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

def search
    @@re = Post.search(params[:search])
end
  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        # SampleMailer.send_when_create('takuma012011@gmail.com').deliver_now
        format.html { redirect_to '/', notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :price, :text, :zyoutai,:img)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clean_blogs_helper.rb
module CleanBlogsHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
      base_title = "Clean Blog"
      if page_title.empty?
          base_title
      else
          "#{base_title} - #{page_title}"
      end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/clean_blogs/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                  <center>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    </center>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Mrukari 2020</p>
            </div>
        </div>
    </div>
</footer>

app/views/clean_blogs/_header.html.erb
<% if current_page?(root_path) %>
    <header class="intro-header" style="background-image:
    url('/assets/clean_blog/home-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>マルカリ</h1>
                    <hr class="small">
                    <span class="subheading">いっぱい売っていっぱい買いましょう</span>


                    <%= form_tag result_path, :method => 'get'  do %>
                      <form class="form-control" required >
                  <%= text_field_tag(:search, params[:search] ,{:placeholder => "例) 本、パソコン", class: "black_pc" } )%>
                  <p></p>
                    <button type="submit" submit_tag="Search" name="Search" class="btn btn-primary" style="width:300px;height:50px;" >検索</button>
                    </form>
                    <%end%>

                </div>
            </div>
        </div>
    </div>
    </header>
<% elsif current_page?(about_path) %>
    <header class="intro-header" style="background-image:
    url('/assets/clean_blog/about-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="page-heading">
                    <h1>About Me</h1>
                    <hr class="small">
                    <span class="subheading">This is what I do.</span>
                </div>
            </div>
        </div>
    </div>
    </header>
<% elsif current_page?(post_path) %>
    <header class="intro-header" style="background-image:
    url('/assets/clean_blog/post-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1>Man must explore, and this is exploration at its greatest</h1>
                    <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
                    <span class="meta">Posted by <a href="#">Start Bootstrap</a> on August 24, 2014</span>
                </div>
            </div>
        </div>
    </div>
    </header>
<% elsif current_page?(contact_path) %>
    <header class="intro-header" style="background-image:
    url('/assets/clean_blog/contact-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="page-heading">
                    <h1>Contact Me</h1>
                    <hr class="small">
                    <span class="subheading">Have questions? I have answers (maybe).</span>
                </div>
            </div>
        </div>
    </div>
    </header>
<% end %>


<style>
  .black_pc{
    margin-top: 20px;
    width: 500px;
    height: 40px;
    color: #000000;
  }
  .searchButton{
    margin-top: 30px;
    width: 300px;
    height: 200px;
  }
</style>

app/views/clean_blogs/_navigation.html.erb
<ul>
	<li><a class="active" href="/">Home</a></li>
	<li><a href="podex">出品する</a></li>
	<!-- <li><a href="#contact">Contact</a></li>
	<li><a href="#about">About</a></li> -->
</ul>

<style type="text/css">

  ul {
  	list-style-type: none;
  	margin: 0;
  	padding: 0;

		overflow: hidden;
  	background-color: #1b2538;
  }
  li {
  	float: left;
  	border-right: 1px solid #bbbbbb;
  }
  li:last-child {
  	border-right: none;
  }
  li a {
  	display: block;
  	color: white;
  	text-align: center;
  	padding: 14px 16px;
  	text-decoration: none;
    background-color: #da3c41;
  }
  li a:hover:not(.active) {
  	background-color: #a9bce2;
  }
  .active {
  	background-color: #da3c41;
  }

</style>

app/views/clean_blogs/_shim.html.erb
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/clean_blogs/about.html.erb
<% provide(:title, "About") %>

<%= render 'shim' %>
<%= render 'navigation' %>
<%= render 'header' %>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
        </div>
    </div>
</div>

<br>

<%= render 'footer' %>

app/views/clean_blogs/contact.html.erb
<% provide(:title, "Contact") %>

<%= render 'shim' %>
<%= render 'navigation' %>
<%= render 'header' %>

    <!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
            <form name="sentMessage" id="contactForm" novalidate>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Name</label>
                        <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Email Address</label>
                        <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Phone Number</label>
                        <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <label>Message</label>
                        <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <br>
                <div id="success"></div>
                <div class="row">
                    <div class="form-group col-xs-12">
                        <button type="submit" class="btn btn-default">Send</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<br>

<%= render 'footer' %>

app/views/clean_blogs/index.html.erb
<title>Clean Blog</title>

<%= render 'shim' %>
<%= render 'navigation' %>
<%= render 'header' %>

<!-- Main Content -->
<%= render 'photo' %>

<%= render 'footer' %>

app/views/clean_blogs/post.html.erb
<% provide(:title, "Sample Post") %>

<%= render 'shim' %>
<%= render 'navigation' %>
<%= render 'header' %>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>

                <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>

                <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>

                <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>

                <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>

                <h2 class="section-heading">The Final Frontier</h2>

                <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

                <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

                <blockquote>The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>

                <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>

                <h2 class="section-heading">Reaching for the Stars</h2>

                <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>

                <%= image_tag('clean_blog/post-sample-image.jpg') %>

                <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>

                <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>

                <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>

                <p>Placeholder text by <a href="http://spaceipsum.com/">Space Ipsum</a>. Photographs by <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>.</p>
            </div>
        </div>
    </div>
</article>

<br>

<%= render 'footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarukariApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/clean_blog.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b>名前：</b>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <b>メールアドレス：</b>
    <%= form.text_field :mailadd %>
  </div>


  <div class="field">
    <b>電話番号：</b>
    <%= form.text_field :phonenum %>
  </div>

   <div class="field">
     <b>住所：</b>
    <%= form.text_field :apply %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mailadd</th>
      <th>Phonenum</th>
      <th>Apply</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.mailadd %></td>
        <td><%= member.phonenum %></td>
        <td><%= member.apply %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<center>
<h1>購入者情報を登録</h1>

<%= render 'form', member: @member %>

 <%# link_to 'Back', members_path  %>
<%= link_to 'Back', '/' %>

</center>

app/views/members/show.html.erb
<center>
<p id="notice"><%= notice %></p>

<h1>購入しました</h1>
<p>
  <strong>名前:</strong>
  <%= @member.name %>
</p>

  <strong>メールアドレス:</strong>
  <%= @member.mailadd %>
</p>

<p>
  <strong>携帯番号:</strong>
  <%= @member.phonenum %>
</p>

<p>
  <strong>住所:</strong>
  <%= @member.apply %>
</p>

<%# 購入したものは削除する %>
<% Post.find(@@ids).destroy %>
<!--
<%= link_to 'Edit', edit_member_path(@member) %>
<%= link_to '戻る', members_path %>
-->
<%= link_to '戻る', '/' %>

</center>

app/views/posts/_form.html.erb
<center>
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field test">
    <h3>商品名</h3>
    <%= form.text_field :name%>
  </div>

  <div class="field">
    <h3>価格</h3>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <h3>説明文</h3>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <h3>商品の状態</h3>
    <%= form.text_field :zyoutai %>
  </div>

  <div class="field">
    <h3>添付画像</h3>
    <%= form.file_field :img %>
  </div>

  <div class="actions submitButton">
    <%= form.submit value: "出品する" %>
  </div>
<% end %>

</center>

<style>
  .test text_field{
    /* -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px; */
  }

  .submitButton{
    padding-top: 30px;
  }
</style>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Text</th>
      <th>Zyoutai</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.price %></td>
        <td><%= post.text %></td>
        <td><%= post.zyoutai %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<%= render 'clean_blogs/navigation' %>

<center><h1>出品する</h1>

<%= render 'form', post: @post %>

<%= link_to '戻る', posts_path %>
</center>


<style>
  h1 {
  color: #364e96;/*文字色*/
  padding: 0.5em 0;/*上下の余白*/
  border-top: solid 3px #364e96;/*上線*/
  border-bottom: solid 3px #364e96;/*下線*/
}
</style>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @post.price %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<p>
  <strong>Zyoutai:</strong>
  <%= @post.zyoutai %>
</p>


<p>
  <strong>img:</strong>
  <img src="<%= @post.img.url %>" alt="">
  <p><%= @post.img.url %></p>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>